FROM vulnerables/web-dvwa:latest
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y netcat-traditional