FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
    python3 \
    python3-venv \
    python3-dev \
    python3-pip \
    curl \
    git \
    build-essential \
    libssl-dev \
    libffi-dev \
    wget \
    gnupg

RUN apt-get install -y \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    libbz2-dev

RUN wget https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz && \
    tar -xf Python-3.10.16.tgz && \
    cd Python-3.10.16 && \
    ./configure --enable-optimizations && \
    make -j $(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.10.16 Python-3.10.16.tgz && \
    ln -sf /usr/local/bin/python3.10 /usr/bin/python3.10

RUN apt-get install -y \
    nmap \
    nikto \
    hydra \
    metasploit-framework

RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.10 1

RUN curl -sSL https://install.python-poetry.org | python3.10 -
ENV PATH="/root/.local/bin:$PATH"

RUN poetry config virtualenvs.create false

WORKDIR /app

COPY pyproject.toml poetry.lock* ./
RUN poetry install --no-interaction --no-ansi --no-root || echo "Instalación de dependencias pendiente"
COPY custom-sec-tools.py ./
CMD ["python3", "custom-sec-tools.py"]