services:
  custom-sec:
    build:
      context: .
      dockerfile: Dockerfile-custom-sec-tools-ollama
    container_name: custom-sec
    restart: no
    depends_on:
      ollama:
        condition: service_healthy
      vulnerable-app:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - TARGET_HOST=172.18.0.2
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "6g"
    networks:
      - sec-net
    cap_add:
      - SYS_TIME
      - NET_ADMIN
      - NET_RAW
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./results:/results
    ports:
      - "4444-4450:4444-4450"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11436:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./ollama_logs:/logs
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_THREADS=2
      - OLLAMA_CONTEXT_LENGTH=8192
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: "/ollama-entrypoint.sh"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - sec-net

  vulnerable-app:
    build:
      context: .
      dockerfile: Dockerfile-dvwa
    container_name: vulnerable-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=dvwa
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512m"
    networks:
      - sec-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: msf
      POSTGRES_PASSWORD: msfpassword
      POSTGRES_DB: msf
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msf"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512m"
    networks:
      - sec-net

volumes:
  ollama_models:
  ollama_logs:
  postgres-data:

networks:
  sec-net:
    driver: bridge