services:
  custom-sec:
    build:
      context: .
      dockerfile: Dockerfile-custom-sec-tools-ollama
    container_name: custom-sec
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - sec-net
    cap_add:
      - SYS_TIME  # Permite ajustar la hora del sistema

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./ollama_logs:/logs
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_THREADS=2  # Reducimos aún más a 2 hilos
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: "/ollama-entrypoint.sh"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "2"  # Reducimos a 2 CPUs
          memory: "4g"
    networks:
      - sec-net

volumes:
  ollama_models:
  ollama_logs:

networks:
  sec-net:
    driver: bridge